services:
  app-a:
    build:
      context: ./packages/example-app/
    container_name: app-a
    hostname: app-a
    environment:
      - APP_NAME=a
      - METRICS_HOST=app-a
      - METRICS_PORT=9464
      - TRACES_HOST=jaeger
      - TRACES_PORT_PORT=6831
    ports:
      - 3000:3000
    restart: unless-stopped

  app-b:
    build:
      context: ./packages/example-app/
    container_name: app-b
    hostname: app-b
    environment:
      - APP_NAME=b
      - METRICS_HOST=app-a
      - METRICS_PORT=9464
      - TRACES_HOST=jaeger
      - TRACES_PORT_PORT=6831
    ports:
      - 3001:3000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    hostname: jaeger
    ports:
      - 16686:16686
    restart: unless-stopped

