services:
  app-a:
    build: ./packages/app-a
    container_name: app-a
    hostname: app-a
    environment:
      - APP_NAME=app-a
      - METRICS_HOST=app-a
      - METRICS_PORT=9464
      - TRACES_HOST=jaeger
      - TRACES_PORT_PORT=6831
    ports:
      - 3000:3000
    restart: unless-stopped

  app-b:
    build: ./packages/app-b
    container_name: app-b
    hostname: app-b
    environment:
      - APP_NAME=app-b
      - METRICS_HOST=app-a
      - METRICS_PORT=9464
      - TRACES_HOST=jaeger
      - TRACES_PORT_PORT=6831
    ports:
      - 3001:3000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    hostname: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 5778:5778 
      - 16686:16686 
      - 4317:4317 
      - 4318:4318 
      - 14250:14250 
      - 14268:14268 
      - 14269:14269 
      - 9411:9411 
    restart: unless-stopped
volumes:
  prom_data:
